=begin
#SignRequest API

#API for SignRequest.com

OpenAPI spec version: v1
Contact: tech-support@signrequest.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SignRequestClient::ApiTokensApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiTokensApi' do
  before do
    # run before each test
    @instance = SignRequestClient::ApiTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiTokensApi' do
    it 'should create an instance of ApiTokensApi' do
      expect(@instance).to be_instance_of(SignRequestClient::ApiTokensApi)
    end
  end

  # unit tests for api_tokens_create
  # 
  # 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AuthToken]
  describe 'api_tokens_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_tokens_delete
  # 
  # 
  # @param key A unique value identifying this api token.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_tokens_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_tokens_list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :limit Number of results to return per page.
  # @return [InlineResponse200]
  describe 'api_tokens_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_tokens_read
  # 
  # 
  # @param key A unique value identifying this api token.
  # @param [Hash] opts the optional parameters
  # @return [AuthToken]
  describe 'api_tokens_read test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
