=begin
#SignRequest API

#API for SignRequest.com

OpenAPI spec version: v1
Contact: tech-support@signrequest.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SignRequestClient::EventsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @instance = SignRequestClient::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@instance).to be_instance_of(SignRequestClient::EventsApi)
    end
  end

  # unit tests for events_list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :document__uuid 
  # @option opts [String] :document__external_id 
  # @option opts [String] :document__signrequest__who 
  # @option opts [String] :document__signrequest__from_email 
  # @option opts [String] :document__status 
  # @option opts [String] :document__user__email 
  # @option opts [String] :document__user__first_name 
  # @option opts [String] :document__user__last_name 
  # @option opts [String] :delivered 
  # @option opts [String] :delivered_on 
  # @option opts [String] :timestamp 
  # @option opts [String] :status 
  # @option opts [String] :event_type 
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :limit Number of results to return per page.
  # @return [InlineResponse2004]
  describe 'events_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for events_read
  # 
  # 
  # @param id A unique integer value identifying this event.
  # @param [Hash] opts the optional parameters
  # @return [Event]
  describe 'events_read test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
