=begin
#SignRequest API

#API for SignRequest.com

OpenAPI spec version: v1
Contact: tech-support@signrequest.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SignRequestClient::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = SignRequestClient::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(SignRequestClient::WebhooksApi)
    end
  end

  # unit tests for webhooks_create
  # 
  # 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'webhooks_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_delete
  # 
  # 
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'webhooks_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :limit Number of results to return per page.
  # @return [InlineResponse2009]
  describe 'webhooks_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_partial_update
  # 
  # 
  # @param uuid 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'webhooks_partial_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_read
  # 
  # 
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'webhooks_read test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_update
  # 
  # 
  # @param uuid 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'webhooks_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
