=begin
#SignRequest API

#API for SignRequest.com

OpenAPI spec version: v1
Contact: tech-support@signrequest.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignRequestClient::SigningLog
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SigningLog' do
  before do
    # run before each test
    @instance = SignRequestClient::SigningLog.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SigningLog' do
    it 'should create an instance of SigningLog' do
      expect(@instance).to be_instance_of(SignRequestClient::SigningLog)
    end
  end
  describe 'test attribute "pdf"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "security_hash"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

